### ISSUE TITLE
Responsible Disclosure

### ISSUE THREAD

**Issue by geeknik** [f13rce/KFA-KilledFromAfar#1]
Good morning, I hope this message finds you well during these challenging times. I apologize for opening this unrelated issue here, but we were unable to find another way to contact you. It has come to our attention that a file on your `f13rce.net` website is vulnerable to XSS and we'd like to privately share the details with you.

**Comment by f13rce** [comment]
Hi @geeknik , apologies for the late response. I'm interested in your find. Can I use the email from the website you have linked to your profile? You could also add me on Discord (f13rce#1313).
Thanks

**Comment by geeknik** [comment]
You can use that email and I've added you on Discord.

**Comment by f13rce** [comment]
Problem resolved. Thank you for the report!
